### ISSUE TITLE
Feedback for “Coolify”

### ISSUE THREAD

**Issue by packet3** [gitroomhq/postiz-docs#49]
Hello,

The documentation is incorrect for the docker compose file,  I spent a few days trying to get this to work and I've now got a working version,  this is my full docker compose file I have added comments in CAPS, I hope this helps someone.

```
services:
  postiz:
    image: 'ghcr.io/gitroomhq/postiz-app:latest'
    container_name: postiz
    restart: always
    environment:
      MAIN_URL: 'https://[DOMAIN_HERE]'
      FRONTEND_URL: 'https://[DOMAIN_HERE]'
      NEXT_PUBLIC_BACKEND_URL: 'https://[DOMAIN_HERE]/api'
      JWT_SECRET: [SOME_SECRET]
      DATABASE_URL: 'postgresql://postiz-user:postiz-password@postiz-postgres:5432/postiz-db-local'
      REDIS_URL: 'redis://postiz-redis:6379'
      BACKEND_INTERNAL_URL: 'http://localhost:3000'
      IS_GENERAL: 'true'
      STORAGE_PROVIDER: local
      UPLOAD_DIRECTORY: /uploads
      NEXT_PUBLIC_UPLOAD_DIRECTORY: /uploads
    volumes:
      - 'postiz-config:/config/'
      - 'postiz-uploads:/uploads/'
    ports:
      - '5000:5000'
    networks:
      - postiz-network
      - coolify => [I NEEDED TO ADD THIS]
    
    labels:
      - traefik.enable=true
      - traefik.http.routers.[ANY_ROUTER_NAME_HERE].rule=Host(`[YOUR_DOMAIN_HERE]`) && PathPrefix(`/`)
      - traefik.http.routers.[ANY_ROUTER_NAME_HERE_MUST_MATCH_NAME_FROM_ABOVE].entryPoints=https
      - traefik.http.routers.[ANY_ROUTER_NAME_HERE_MUST_MATCH_NAME_FROM_ABOVE].tls.certresolver=letsencrypt
      - traefik.http.services.[ANY_ROUTER_NAME_HERE_MUST_MATCH_NAME_FROM_ABOVE].loadbalancer.server.port=5000
 
      
    depends_on:
      postiz-postgres:
        condition: service_healthy
      postiz-redis:
        condition: service_healthy
  postiz-postgres:
    image: 'postgres:14.5'
    container_name: postiz-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postiz-password
      POSTGRES_USER: postiz-user
      POSTGRES_DB: postiz-db-local
    volumes:
      - 'postgres-volume:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    networks:
      - postiz-network
    healthcheck:
      test: 'pg_isready -U postiz-user -d postiz-db-local'
      interval: 10s
      timeout: 3s
      retries: 3
  postiz-redis:
    image: 'redis:7.2'
    container_name: postiz-redis
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: 'redis-cli ping'
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - 'postiz-redis-data:/data'
    networks:
      - postiz-network
volumes:
  postgres-volume:
    external: false
  postiz-redis-data:
    external: false
  postiz-config:
    external: false
networks:
  coolify: [I NEEDED TO ADD THIS]
    external: true
  postiz-network:
    external: false
```
