### ISSUE TITLE
Redirecting Inifinitely between / and /launches after deploy

### ISSUE THREAD

**Issue by frankie0736** [gitroomhq/postiz-docs#82]
Hi Postiz team,

I deployed postiz with caddy reverse proxy on my server: [https://wa.210k.cc/](https://wa.210k.cc/)
but when I visiting it keeps redirecting between / and /launches.

below are my config files, would you please help, thanks so much.

here is a video: [https://meeting.tencent.com/crm/KEVD98Dd7a](https://meeting.tencent.com/crm/KEVD98Dd7a)

this is my caddy config file:
```json
wa.210k.cc {
        reverse_proxy * postiz:5000
}
```

this is `my docker-compose.yml` file:

```yml
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    networks:
      - postiz-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - /home/fx/postiz/caddy_config:/config
      - /home/fx/postiz/caddy_config/Caddyfile:/etc/caddy/Caddyfile
  postiz:
    image: ghcr.io/gitroomhq/postiz-app:latest
    container_name: postiz
    restart: always
    environment:
      MAIN_URL: "https://wa.210k.cc"
      FRONTEND_URL: "https://wa.210k.cc"
      NEXT_PUBLIC_BACKEND_URL: "https://wa.210k.cc/api"
      JWT_SECRET: "11111111"
 
      DATABASE_URL: "postgresql://postiz-user:postiz-password@postiz-postgres:5432/postiz-db-local"
      REDIS_URL: "redis://postiz-redis:6379"
      BACKEND_INTERNAL_URL: "http://localhost:3000"
      IS_GENERAL: "true" # Required for self-hosting.
      STORAGE_PROVIDER: "local"
      UPLOAD_DIRECTORY: "/uploads"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"
    volumes:
      - postiz-config:/config/
      - postiz-uploads:/uploads/
    ports:
      - 5000:5000
    networks:
      - postiz-network
    depends_on:
      postiz-postgres:
        condition: service_healthy
      postiz-redis:
        condition: service_healthy
 
  postiz-postgres:
    image: postgres:17-alpine
    container_name: postiz-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postiz-password
      POSTGRES_USER: postiz-user
      POSTGRES_DB: postiz-db-local
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - postiz-network
    healthcheck:
      test: pg_isready -U postiz-user -d postiz-db-local
      interval: 10s
      timeout: 3s
      retries: 3
  postiz-redis:
    image: redis:7.2
    container_name: postiz-redis
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postiz-redis-data:/data
    networks:
      - postiz-network
 
 
volumes:
  postgres-volume:
    external: false
 
  postiz-redis-data:
    external: false
 
  postiz-config:
    external: false
 
  postiz-uploads:
    external: false

  caddy_data:
    external: false
 
networks:
  postiz-network:
    external: false

```
